[package]
name = "rxscan"
version = "0.1.0"
edition = "2024"

[dependencies]
clap.workspace=true
time.workspace=true
tokio.workspace=true
anyhow.workspace=true
tracing.workspace=true
tracing-subscriber.workspace=true
tracing-log.workspace=true
console = "0.16.1"
console-subscriber = "0.5.0"
serde.workspace=true
serde_json.workspace=true
rxscan-core={ path = "../rxscan-core"}
rxscan-port={ path = "../rxscan-port"}
rxscan-sys={ path = "../rxscan-sys"}
rxscan-web={ path = "../rxscan-web"}


